# Generated by Django 4.1 on 2022-08-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='itemimg/placehomder.jpg', null=True, upload_to=''),
        ),
    ]
